name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run security checks
        run: bandit -r .

      - name: Check PEP8 compliance
        run: |
          if ! pycodestyle .; then
            exit 1
          fi

      - name: Deploy code
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DG_HOST }}
          username: ${{ secrets.DG_USERNAME }}
          key: ${{ secrets.SSH_PK }}
          source: "./script.py"
          target: "/home"
          # script: |
            # scp -i ${{ secrets.SSH_PK }} -r ./* ${{ secrets.DG_USERNAME }}@${{ secrets.DG_HOST }}:/home/
